- name: configuring Erlang repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: configuring rabbitmq repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: Installing rabbitmq 
  ansible.builtin.package:
    name: rabbitmq-server 
    state: present 

- name: starting rabbitmq
  ansible.builtin.service:
    name: rabbitmq-server  
    state: started         
    enabled: yes

- name: Creating App User for Rabbitmq 
  community.rabbitmq.rabbitmq_user:
    user: {{APPUSER}}
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present 