- name: Installing maven 
  ansible.builtin.package:
    name: maven 
    state: present 

# call create user role
- name: calling create user role from common role 
  ansible.builtin.include_role: 
    name: common
    tasks_from: create_user

# call download and extract role
- name: calling download and extract from common role 
  ansible.builtin.include_role: 
    name: common
    tasks_from: download_cleanup

- name: Generating Artifacts
  ansible.builtin.shell: mvn clean package  &&  mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
  args:
    chdir: /home/{{APPUSER}}/{{COMPONENT}}/


# call config service file
- name: calling config service role from common role 
  ansible.builtin.include_role: 
    name: common
    tasks_from: config-service