- name: Installing python and dependencies
  ansible.builtin.yum:
    name:
      - python36
      - gcc 
      - python3-devel
    state: present
  
# call create user role
- name: calling create user role from common role 
  ansible.builtin.include_role: 
    name: common
    tasks_from: create_user

# call download and extract role
- name: calling download and extract from common role 
  ansible.builtin.include_role: 
    name: common
    tasks_from: download_cleanup