- name: Demo on using variables
  hosts: all
  vars:
    URL: play.google.com    # it is a global varibale declaration
  vars_files: demo_vars.yml
  vars_prompt:
    - name: PURL
      prompt: ENter the purl
      private: false

  tasks:
    - name: printing the URL task
      ansible.builtin.debug:
        msg: The defined url is {{URL}}

    - name: printing the URL second task
      ansible.builtin.debug:
        msg: The defined seocnd url is {{URL}}
      vars:
        URL: fb.com    # task/locla variable: scope of it is inside task only

    - name: printing the URL alone
      ansible.builtin.debug:
        msg: "{{URL}}"
      vars:
        URL: google.com    # task/locla variable: scope of it is inside task only

    - name: suply variable from command line
      ansible.builtin.debug:
        msg: "{{CMD_URL}}"

    - name: Printing the variables from a file 
      ansible.builtin.debug:
        msg: "{{var_from_file}}"

    - name: Printing prompt url  
      ansible.builtin.debug:
        msg: "{{PURL}}"
         
# command line variables > local variables > global variables > file 

