# in package module, state has present, absent, latest.
# present: wether to install; absent: remove a package
# latest: update only if available

- name: demo on package installation
  hosts: all
  ansible.builtin.package:
    name: 
