# in package module, state has present, absent, latest.
# present: to install; absent: remove a package
# latest: update only if available

- name: demo on package installation
  hosts: all
  tasks: 
    - name: Installing nginx 
      ansible.builtin.package:
        name: nginx 
        state: present
